name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - ready_for_review

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: dependabot
          MERGE_METHOD: squash
          MERGE_FORKS: false
          UPDATE_LABELS: dependabot
