name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - ready_for_review

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"
          MERGE_LABELS: dependencies
          MERGE_METHOD: squash
          MERGE_FORKS: false
          UPDATE_LABELS: dependencies
          DELETE_BRANCH_AFTER_MERGE: true
